export const AUTH_START = 'AUTH_START';
export const GET_WORKFLOWS = 'GET_WORKFLOWS';
export const GET_PROCESSES = 'GET_PROCESSES';
export const GET_JSON_RENDER = 'GET_JSON_RENDER';
export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';
